In [20]:
#Exercicio 1
import numpy

matrix = numpy.arange(1, 26).reshape(5, 5)

print(matrix)
print("Soma dos elementos da diagonal:", numpy.sum(numpy.diagonal(matrix)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Soma dos elementos da diagonal: 65


In [21]:
#Exercicio 2
matrix = numpy.arange(2, 51, 2).reshape(5, 5)

print(matrix)
print("Soma dos elementos das linhas :", numpy.sum(matrix, axis=0))
print("Soma dos elementos das colunas :", numpy.sum(matrix, axis=1))
print("Media dos elementos da ultima linha :", numpy.mean(matrix[4]))
print("Media dos elementos da ultima coluna :", numpy.mean(matrix[0:5, 4]))

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
Soma dos elementos das linhas : [110 120 130 140 150]
Soma dos elementos das colunas : [ 30  80 130 180 230]
Media dos elementos da ultima linha : 46.0
Media dos elementos da ultima coluna : 30.0


In [22]:
array = numpy.random.normal(0, 3, size=(5, 5))

a = array.flatten()
print(a,"Elemento retirado:",  numpy.max(a))
a[numpy.argmax(a)] = 0
print("Lista depois da remocao:\n", a)


[-0.67585312  4.83311362 -2.56404669  4.81856379  2.38206019  0.11242689
  1.51133943 -1.26579813 -4.25813975  1.94274302  4.29037002  2.2865131
 -1.49289744 -0.15277483  0.62083066 -6.74578429  4.13778064 -0.77271723
  0.43913641 -0.29089288 -0.67553524  3.76091106 -1.96696823  0.4946067
  0.55200285] Elemento retirado: 4.833113621212235
Lista depois da remocao:
 [-0.67585312  0.         -2.56404669  4.81856379  2.38206019  0.11242689
  1.51133943 -1.26579813 -4.25813975  1.94274302  4.29037002  2.2865131
 -1.49289744 -0.15277483  0.62083066 -6.74578429  4.13778064 -0.77271723
  0.43913641 -0.29089288 -0.67553524  3.76091106 -1.96696823  0.4946067
  0.55200285]


In [23]:
#Exercicio 4
a = numpy.random.uniform(size=(5, 3))
b = numpy.random.uniform(size=(3, 4))

c = a.dot(b)
print (c)

[[0.68562172 1.18640374 1.01219574 1.17837986]
 [0.71863539 1.59947821 1.46629248 1.27211135]
 [0.28104323 0.59401429 0.51114694 0.6541612 ]
 [0.69633799 1.21446256 1.07638498 0.97046752]
 [0.52345335 1.10019863 0.95889501 1.13358877]]


In [24]:
#Exercicio 5
a = numpy.arange(9, dtype=numpy.float32).reshape(3, 3)

b = a.astype(numpy.int32)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
#Exercicio 6
a = numpy.random.uniform(size=(8, 8))
print(a)
#a[0:8, 7]
somado = numpy.add(a[0:8, 7], 10)
print("Soma 10 nos elementos da ultima coluna :\n", somado)

[[0.52936124 0.07495243 0.15104453 0.61138772 0.18126226 0.95967482
  0.43977457 0.12973676]
 [0.028296   0.82289897 0.66447546 0.05987721 0.90035505 0.97094365
  0.2300732  0.77650487]
 [0.12603709 0.94024465 0.88113089 0.35900704 0.46545402 0.2529062
  0.43870303 0.09511365]
 [0.65831418 0.70454154 0.13123236 0.39412251 0.57942746 0.28907015
  0.46093384 0.02837666]
 [0.94997041 0.9922356  0.2879719  0.6351879  0.68419848 0.25273136
  0.58983891 0.56772972]
 [0.65097451 0.18314444 0.20380823 0.88946974 0.88413774 0.02212201
  0.72274587 0.34325257]
 [0.34297549 0.91328193 0.27281982 0.00241796 0.34009066 0.51559697
  0.03806573 0.10852365]
 [0.58871711 0.67927336 0.10150188 0.82811438 0.21465987 0.37281242
  0.81091733 0.32094137]]
Soma 10 nos elementos da ultima coluna :
 [10.12973676 10.77650487 10.09511365 10.02837666 10.56772972 10.34325257
 10.10852365 10.32094137]


In [26]:
#Exercicio 7
array = numpy.arange(1, 17).reshape(4,4).transpose()

print(array)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [27]:
#Exercicio 8
a = numpy.array([[0,3,4,5], [7, 10, 9, 2]])
b = numpy.array([[1,4,9,12], [15, 22, 19, 17]])

c = numpy.stack((a, b)).reshape(4,4)

print(c)

[[ 0  3  4  5]
 [ 7 10  9  2]
 [ 1  4  9 12]
 [15 22 19 17]]


In [28]:
#Exercicio 9
import csv

arq = open('actors.csv', "r")
reader = csv.reader(arq)
next(reader)


actor = []
total_gross = []
number_of_movies = []
average_per_movie = []
first_movie = []
gross = []


for line in reader:
    
    actor.append(line[0])
    total_gross.append(float(line[1]))
    number_of_movies.append(int(line[2]))
    average_per_movie.append(float(line[3]))
    first_movie.append(line[4])
    gross.append(float(line[5]))
    
print("Quantidade de filmes:", number_of_movies[numpy.argmax(number_of_movies)], "Autor:",
      actor[numpy.argmax(number_of_movies)]
     )
print("Media de quantidade de filmes:", numpy.mean(number_of_movies))
print("Media por filme:", average_per_movie[numpy.argmax(average_per_movie)], "Autor:",
      actor[numpy.argmax(average_per_movie)]
     )
print("Maior Gross:", gross[numpy.argmax(gross)], "Filme:",
      first_movie[numpy.argmax(gross)]
     )

Quantidade de filmes: 79 Autor: Robert DeNiro
Media de quantidade de filmes: 37.88
Media por filme: 451.8 Autor: Anthony Daniels
Maior Gross: 936.7 Filme: Star Wars: The Force Awakens
